set -U tide_git_bg_color $_thm_surface_0
set -U tide_git_bg_color_unstable $_thm_surface_0
set -U tide_git_bg_color_urgent $_thm_red
set -U tide_git_color_branch $_thm_fg
set -U tide_git_color_conflicted $_thm_fg
set -U tide_git_color_dirty $_thm_fg
set -U tide_git_color_operation $_thm_fg
set -U tide_git_color_staged $_thm_fg
set -U tide_git_color_stash $_thm_fg
set -U tide_git_color_untracked $_thm_fg
set -U tide_git_color_upstream $_thm_fg
