[packageManagers.paru]

root = false
command = ""
args = [
  "-S",
  "--needed",
  "--noconfirm",
  "--skipreview",
]

drivers = [
  "ncurses5-compat-libs",
]

packages = [
  "bun-bin",
  "google-chrome",
  "opencode-bin",
  "sesh",
  "sing-box",
  "tlrc",
]

[packageManagers.paru.minimal]

packages = [
  "bun-bin",
]
