rootNodeIdentities = [
  "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEk2NJ8q9mBxCECOFt9A43uJuJjvwOFzn484CsTpAhoxYQ7wz3b5prO/i7etXApxu2sHzP+rrgAkgVlqGiTLYGI= MacBook-Air@secretive.MacBook-Air.local",
]
