input {
  file {
    path => "/var/log/sing-box/sing-box.log"
    start_position => "end"
    sincedb_path => "/home/linuxbrew/.linuxbrew/var/lib/logstash/sincedb-sing-box"
    mode => "tail"
  }
}

filter {
  mutate {
    add_field => {
      "service" => "sing-box"
      "log_type" => "proxy"
    }
  }
}

output {
  kafka {
    bootstrap_servers => "127.0.0.1:9092"
    topic_id => "sing-box-logs"
    codec => json
    acks => "all"
  }
}
