[flavor]
light = "catppuccin-latte"
dark = "catppuccin-mocha"

[git]
added_sign = "+"
clean_sign = ""
deleted_sign = "x"
ignored_sign = ""
modified_sign = "~"
unknown_sign = ""
untracked_sign = "?"
updated_sign = ""

[icon]
prepend_conds = [
  { if = "dir & hovered", text = "" },
  { if = "dir", text = "" },
]

prepend_dirs = [
  # { name = "Applications", text = "󱋣" },
  { name = "Desktop", text = "󰴉" },
  { name = "Documents", text = "󰲂" },
  { name = "Downloads", text = "󰉍" },
  # { name = "Library", text = "" },
  { name = "Movies", text = "󰿎" },
  { name = "Music", text = "󱍙" },
  { name = "Pictures", text = "󰉏" },
  { name = "Public", text = "" },
  { name = "Shared", text = "" },
]

prepend_globs = [
  { url = "**/containers/",   text = "" },
  { url = "**/**.container",  text = "" },
  { url = "**/share/",        text = "" },
  { url = "**/systemd/",      text = "" },
  { url = "**/**.service",    text = "" },
  { url = "**/**.timer",      text = "󱤦" },
  { url = "**/ssh*/",         text = "󰢬" },
  { url = "**/**.tmpl",       text = "󰅩" },
  { url = "**/*trash*/",      text = "" },
  { url = "**/*trash*/**",    text = "" },
  {
    url  = "**/*.{7z,bz,bz2,bz3,gz,lz,lz4,lzma,rar,tar,tbz,tbz2,tgz,txz,xz,zst,zip}",
    text = ""
  },
]
