#cloud-config

# Meta
# preserve_hostname: true
# hostname: ec2
# fqdn: ec2.er-meng.com
# prefer_fqdn_over_hostname: false
timezone: Asia/Tokyo

# Users
users:
  - default
  - name: chao
    groups: wheel
    lock_passwd: false
    passwd: "$6$rounds=500000$ximEWTUwm/A2CZJR$mQfNzRu2N2I.ili/wAYe6o6D9ozBsZTrWlOysdy2D2MMocanhqO3rvkjv/4qw5RJJFlbhR28EQEy8fSmf2BHq0"
    sudo: ALL=(ALL) ALL
    shell: /bin/bash
    ssh_authorized_keys: 
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiTuWJDyAsg1BpehtZe5WPVA5sx0QbRVK0KEvd4oxvA apne1-01"

# SSH
allow_public_ssh_keys: true
disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
ssh_pwauth: false

# Swap
swap:
  filename: /swapfile
  size: 2G
  maxsize: 2G

runcmd:
  - [systemctl, restart, sshd]

# Packages
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - git
  - curl

# Misc
updates:
  network:
    when: [boot, hotplug]
